// Served ZIPs live in src/data/zips (generated by scripts/build-zip-data.mjs). Only the map's coverage
// summary (src/data/zips/coverage.json) may be used in client code.
export const homeTerminal = {
  name: 'Corona, CA',
  state: 'CA',
  lat: 33.8753,
  lng: -117.5664,
} as const;
