// Booking modal copy. TODO(client): review every line with 951 Express.
export const bookingCopy = {
  title: 'Get My Instant Quote',
  steps: ['Vehicle & Route', 'Deposit', 'Your Details'],
  close: 'Close',
  confirmClose: {
    title: 'Close this quote?',
    body: 'Your answers are saved on this device until you close the tab.',
    keep: 'Keep editing',
    leave: 'Close',
  },
  route: {
    pickupLabel: 'Pickup ZIP',
    deliveryLabel: 'Delivery ZIP',
    deliveryHintWest: 'Delivery must be in our East region.',
    deliveryHintEast: 'Delivery must be in our West region.',
    checking: 'Checking…',
    lookupError: "We couldn't check that ZIP right now. Please try again or call us.",
    call: 'Call {phone}',
    qualified: '✓ Great news, we service this route.',
  },
  vehicle: {
    heading: 'Your vehicle',
    year: 'Year',
    yearPlaceholder: 'Select year',
    make: 'Make',
    makePlaceholder: 'Start typing a make',
    model: 'Model',
    modelPlaceholder: 'Start typing a model',
    loading: 'Loading…',
    lookupError: "We couldn't load the list. Type it in instead.",
    chip: 'Vehicle size: {label}',
    unknownHeading: "We couldn't match your vehicle. Pick the closest size.",
    unknownNote: 'We confirm your size before pickup.',
    cardExample: 'e.g., {example}',
    largeLabel: 'Large SUV or pickup',
  },
  options: {
    operable: 'Is the vehicle operable?',
    operableYes: 'Yes, it runs and drives',
    operableNo: 'No',
    modified: 'Has it been modified in any way?',
    modifiedYes: 'Yes',
    modifiedNo: 'No, factory stock',
    load: 'Load type',
    loadStandard: 'Standard',
    loadTopDeck: 'Top Deck Load',
    personal: 'Any personal items in the vehicle?',
    yes: 'Yes',
    no: 'No',
  },
  weeks: {
    heading: 'Estimated pickup week · {route}',
    loading: 'Loading available weeks…',
    error: "We couldn't load pickup weeks. Please try again or call us.",
    retry: 'Try again',
    spotsLeft: '{n} spots left',
    oneSpotLeft: '1 spot left',
    full: 'FULL {taken}/{capacity}',
    closed: 'CLOSED',
  },
  terms: {
    prefix: 'I agree to the ',
    link: 'Terms and Conditions',
    newTab: '(opens in a new tab)',
  },
  submit: 'See My Price & Deposit →',
  submitting: 'Calculating…',
  genericError: 'Something went wrong. Please try again or call us.',
  lead: {
    heading: 'Request a personalized quote',
    intro:
      'Large vehicles are priced individually. Tell us how to reach you and we will send a quote.',
    name: 'Full name',
    phone: 'Phone',
    email: 'Email',
    week: 'Preferred pickup week (optional)',
    weekNone: 'No preference',
    weekNote: 'A preference only. We do not hold a spot until you book.',
    notes: 'Notes (optional)',
    submit: 'Request my quote',
    submitting: 'Sending…',
    thanksHeading: 'Thank you!',
    thanksBody:
      'We got your request and will contact you shortly with a personalized quote. No payment is due now.',
    done: 'Done',
  },
  summary: {
    heading: 'Your quote',
    vehicle: 'Vehicle',
    route: 'Route',
    week: 'Pickup week',
    load: 'Load type',
    total: 'Transport total',
    deposit: 'Deposit due today',
    balance: 'Balance due at delivery',
    review: 'We will confirm a few details with you before pickup.',
    back: '← Edit my answers',
    continue: 'Continue to secure payment',
    continueNote: 'Secure online payment is coming soon. Call us to book now.',
  },
} as const;
